#!/bin/bash

source /etc/conf.d/mythbackend

[ -z "$MYTHTV_VERBOSE" ] && MYTHTV_VERBOSE="important,general"
[ -z "$MYTHTV_LOGFILE" ] && MYTHTV_LOGFILE="/var/log/mythtv/mythbackend.log"
[ -z "$MYTHTV_HOME"    ] && MYTHTV_HOME="/etc/mythtv"
[ -z "$MYTHTV_USER"    ] && MYTHTV_USER="mythtv"

HOME="$MYTHTV_HOME"

exec /usr/bin/mythbackend --verbose "$MYTHTV_VERBOSE" --user "$MYTHTV_USER" "$MYTHTV_EXTRAOPTS" --logfile "$MYTHTV_LOGFILE"
